project:
  type: book
  output-dir: "docs"
  preview:
    port: 1313
    browser: false
  resources: "datos"

execute: 
  freeze: auto
  cache: true

website:
  favicon: "img/logos/favicon.ico"
  reader-mode: true
  comments: 
    hypothesis:
      theme: clean
      openSidebar: true

book:
  title: "Prácticas de Estadística con R"
  author: "Alfredo Sánchez Alberca"
  date: "1/6/2022"
  output-file: "estadistica-practicas-r"
  image: img/logos/sticker-estadistica-r.png
  cover-image: img/logos/sticker-estadistica-r.png
  sharing: [twitter, linkedin]
  downloads: [pdf, epub]
  favicon: "img/logos/favicon.ico"
  sidebar: 
    logo: img/logos/aprendeconalf.png
    tools:
      - icon: house-fill
        href: https://aprendeconalf.es
  open-graph: true
  twitter-card: 
    site: "@aprendeconalf"
  chapters:
    - index.qmd
    - 01-intro.qmd
    - 02-preprocesamiento-datos.qmd
    - 03-frecuencias-graficos.qmd
    - 04-descriptiva.qmd
    - 05-regresion.qmd
    - 06-distribuciones-probabilidad.qmd
    - 07-intervalos-confianza.qmd
    
#bibliography: references.bib

format:
  html:
    highlight-style: a11y
    theme:
      dark: darkly
      light: flatly
    html-math-method: mathjax
    code-overflow: wrap
    code-link: true
  pdf:
    documentclass: scrreport
    papersize: a4
    template-partials:
      - before-body.tex
    titlegraphic: img/logos/sticker-estadistica-r.png
    institution: CEU San Pablo
    email: asalber@ceu.es
    web: https://aprendeconalf.es
    logo: img/logos/aprendeconalf.png
    include-in-header:
      - preamble.tex
      - macros.tex
    keep-tex: true
    #mainfont: TeX Gyre Termes
    #mainfontoptions:
    #  - Numbers=Lowercase
    #  - Numbers=Proportional    
    
  epub:
    cover-image: img/logos/sticker-estadistica-r.png



