project:
  type: book
  output-dir: "docs"
  preview:
    port: 1313
    browser: false
  resources: "datos"

execute: 
  freeze: auto
  cache: true

website:
  favicon: "img/logos/favicon.ico"
  reader-mode: true
  comments: 
    hypothesis:
      theme: clean
      openSidebar: true

book:
  title: "Prácticas de Estadística con R"
  author: "Alfredo Sánchez Alberca"
  date: "1/6/2022"
  output-file: "estadistica-practicas-r"
  image: img/logos/sticker-estadistica-r.png
  cover-image: img/logos/sticker-estadistica-r.png
  sharing: [twitter, linkedin]
  downloads: [pdf, epub]
  favicon: "img/logos/favicon.ico"
  sidebar: 
    logo: img/logos/aprendeconalf.png
    tools:
      - icon: house-fill
        href: https://aprendeconalf.es
  open-graph: true
  twitter-card: 
    site: "@aprendeconalf"
  chapters:
    - index.qmd
    - 01-intro.qmd
    - 02-tipos-datos.qmd
    - 03-preprocesamiento-datos.qmd
    - 04-frecuencias-graficos.qmd
    - 05-descriptiva.qmd
    - 06-regresion.qmd
    - 07-distribuciones-probabilidad.qmd
    - 08-intervalos-confianza.qmd
    - 09-contrastes-hipotesis-parametricos.qmd
    - 10-anova.qmd
    
#bibliography: references.bib

format:
  html:
    highlight-style: a11y
    theme:
      dark: darkly
      light: flatly
    html-math-method: mathjax
    code-overflow: wrap
    code-link: true
 



