---
lang: es
# listing: 
#     id: toc
#     type: grid
#     fields: [title, image]
#     sort: title
#     filter-ui: false
---

# Prefacio {.unnumbered}

¡Bienvenido a Prácticas de Estadística con R!

Este libro presenta una recopilación de prácticas de Estadística Descriptiva e Inferencial con el lenguaje de programación [R](https://www.r-project.org/), con problemas aplicados a las Ciencias y las Ingenierías.

No es un libro para aprender a programar con R, ya que solo enseña el uso del lenguaje y de algunos de sus paquetes para resolver problemas de Estadística. Para quienes estén interesados en aprender a programar en este lenguaje, os recomiendo leer este [manual de R](https://aprendeconalf.es/manual-r/).

## Capítulos

1. [Introducción a R](/01-intro.qmd)
1. [Preprocesamiento de datos](02-preprocesamiento-datos.qmd)
1. [Distribuciones de frecuencias y representaciones gráficas](03-frecuencias-graficos.qmd)
1. [Estadística descriptiva](04-descriptiva.qmd)
1. [Regresión](05-regresion.qmd)
1. [Distribuciones de probabilidad.qmd](06-distribuciones-probabilidad.qmd)
1. [Intervalos de confianza para una población](07-intervalos-confianza-una-poblacion.qmd)
1. [Intervalos de confianza para la comparación de dos poblaciones](08-intervalos-confianza-comparacion-dos-poblaciones.qmd)
1. [Contrastes de hipótesis](09-contrastes-hipotesis-parametricos-una-y-dos-poblaciones.qmd)
1. [Análisis de la varianza](10-anova.qmd)

## Licencia

Esta obra está bajo una licencia Reconocimiento – No comercial – Compartir bajo la misma licencia 3.0 España de Creative Commons. Para ver una copia de esta licencia, visite [https://creativecommons.org/licenses/by-nc-sa/3.0/es/](https://creativecommons.org/licenses/by-nc-sa/3.0/es/).

Con esta licencia eres libre de:

- Copiar, distribuir y mostrar este trabajo.
- Realizar modificaciones de este trabajo.

Bajo las siguientes condiciones:

- **Reconocimiento**. Debe reconocer los créditos de la obra de la manera especificada por el autor o el licenciador (pero no de una manera que sugiera que tiene su apoyo o apoyan el uso que hace de su obra).

- **No comercial**. No puede utilizar esta obra para fines comerciales.

- **Compartir bajo la misma licencia**. Si altera o transforma esta obra, o genera una obra derivada, sólo puede distribuir la obra generada bajo una licencia idéntica a ésta.

Al reutilizar o distribuir la obra, tiene que dejar bien claro los términos de la licencia de esta obra.

Estas condiciones pueden no aplicarse si se obtiene el permiso del titular de los derechos de autor.

Nada en esta licencia menoscaba o restringe los derechos morales del autor.